"""Initial schema with new table names and game cartridge model

Revision ID: 05cf4dc4d9ed
Revises: 
Create Date: 2025-02-09 19:48:04.593798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05cf4dc4d9ed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_data_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('openid', sa.String(length=64), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_data_users_id'), 'tb_data_users', ['id'], unique=False)
    op.create_index(op.f('ix_tb_data_users_openid'), 'tb_data_users', ['openid'], unique=True)
    op.create_table('tb_data_borrow_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_type', sa.Enum('book', 'magazine', 'cd', 'vinyl', 'dvd', 'game_cartridge', name='collection_type'), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('borrower_id', sa.Integer(), nullable=False),
    sa.Column('lender_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'returned', name='borrow_status'), nullable=True),
    sa.Column('borrow_date', sa.DateTime(), nullable=True),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('expected_return_date', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['borrower_id'], ['tb_data_users.id'], ),
    sa.ForeignKeyConstraint(['lender_id'], ['tb_data_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_data_borrow_records_id'), 'tb_data_borrow_records', ['id'], unique=False)
    op.create_table('tb_data_libraries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('visibility', sa.Enum('private', 'friends', 'public', name='visibility_type'), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['tb_data_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_data_libraries_id'), 'tb_data_libraries', ['id'], unique=False)
    op.create_table('tb_data_reading_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_type', sa.Enum('book', 'magazine', 'cd', 'vinyl', 'dvd', 'game_cartridge', name='collection_type'), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tb_data_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_data_reading_records_id'), 'tb_data_reading_records', ['id'], unique=False)
    op.create_table('tb_data_books',
    sa.Column('isbn', sa.String(length=13), nullable=True),
    sa.Column('author', sa.String(length=256), nullable=True),
    sa.Column('publisher', sa.String(length=128), nullable=True),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('market_price', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('in_library', 'borrowed', 'given', name='collection_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['tb_data_libraries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_data_books_id'), 'tb_data_books', ['id'], unique=False)
    op.create_index(op.f('ix_tb_data_books_isbn'), 'tb_data_books', ['isbn'], unique=False)
    op.create_table('tb_data_cds',
    sa.Column('isrc', sa.String(length=12), nullable=True),
    sa.Column('artist', sa.String(length=256), nullable=True),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('genre', sa.String(length=64), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('market_price', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('in_library', 'borrowed', 'given', name='collection_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['tb_data_libraries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_data_cds_id'), 'tb_data_cds', ['id'], unique=False)
    op.create_index(op.f('ix_tb_data_cds_isrc'), 'tb_data_cds', ['isrc'], unique=False)
    op.create_table('tb_data_dvds',
    sa.Column('isan', sa.String(length=26), nullable=True),
    sa.Column('director', sa.String(length=256), nullable=True),
    sa.Column('studio', sa.String(length=128), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('genre', sa.String(length=64), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('region_code', sa.String(length=8), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('market_price', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('in_library', 'borrowed', 'given', name='collection_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['tb_data_libraries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_data_dvds_id'), 'tb_data_dvds', ['id'], unique=False)
    op.create_index(op.f('ix_tb_data_dvds_isan'), 'tb_data_dvds', ['isan'], unique=False)
    op.create_table('tb_data_game_cartridges',
    sa.Column('product_code', sa.String(length=32), nullable=True),
    sa.Column('developer', sa.String(length=256), nullable=True),
    sa.Column('publisher', sa.String(length=256), nullable=True),
    sa.Column('platform', sa.String(length=64), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('genre', sa.String(length=64), nullable=True),
    sa.Column('region', sa.String(length=32), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('market_price', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('in_library', 'borrowed', 'given', name='collection_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['tb_data_libraries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_data_game_cartridges_id'), 'tb_data_game_cartridges', ['id'], unique=False)
    op.create_index(op.f('ix_tb_data_game_cartridges_product_code'), 'tb_data_game_cartridges', ['product_code'], unique=False)
    op.create_table('tb_data_magazines',
    sa.Column('issn', sa.String(length=8), nullable=True),
    sa.Column('publisher', sa.String(length=128), nullable=True),
    sa.Column('issue_number', sa.String(length=32), nullable=True),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('market_price', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('in_library', 'borrowed', 'given', name='collection_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['tb_data_libraries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_data_magazines_id'), 'tb_data_magazines', ['id'], unique=False)
    op.create_index(op.f('ix_tb_data_magazines_issn'), 'tb_data_magazines', ['issn'], unique=False)
    op.create_table('tb_data_vinyl_records',
    sa.Column('isrc', sa.String(length=12), nullable=True),
    sa.Column('artist', sa.String(length=256), nullable=True),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('genre', sa.String(length=64), nullable=True),
    sa.Column('rpm', sa.Integer(), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('market_price', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('in_library', 'borrowed', 'given', name='collection_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['tb_data_libraries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_data_vinyl_records_id'), 'tb_data_vinyl_records', ['id'], unique=False)
    op.create_index(op.f('ix_tb_data_vinyl_records_isrc'), 'tb_data_vinyl_records', ['isrc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_data_vinyl_records_isrc'), table_name='tb_data_vinyl_records')
    op.drop_index(op.f('ix_tb_data_vinyl_records_id'), table_name='tb_data_vinyl_records')
    op.drop_table('tb_data_vinyl_records')
    op.drop_index(op.f('ix_tb_data_magazines_issn'), table_name='tb_data_magazines')
    op.drop_index(op.f('ix_tb_data_magazines_id'), table_name='tb_data_magazines')
    op.drop_table('tb_data_magazines')
    op.drop_index(op.f('ix_tb_data_game_cartridges_product_code'), table_name='tb_data_game_cartridges')
    op.drop_index(op.f('ix_tb_data_game_cartridges_id'), table_name='tb_data_game_cartridges')
    op.drop_table('tb_data_game_cartridges')
    op.drop_index(op.f('ix_tb_data_dvds_isan'), table_name='tb_data_dvds')
    op.drop_index(op.f('ix_tb_data_dvds_id'), table_name='tb_data_dvds')
    op.drop_table('tb_data_dvds')
    op.drop_index(op.f('ix_tb_data_cds_isrc'), table_name='tb_data_cds')
    op.drop_index(op.f('ix_tb_data_cds_id'), table_name='tb_data_cds')
    op.drop_table('tb_data_cds')
    op.drop_index(op.f('ix_tb_data_books_isbn'), table_name='tb_data_books')
    op.drop_index(op.f('ix_tb_data_books_id'), table_name='tb_data_books')
    op.drop_table('tb_data_books')
    op.drop_index(op.f('ix_tb_data_reading_records_id'), table_name='tb_data_reading_records')
    op.drop_table('tb_data_reading_records')
    op.drop_index(op.f('ix_tb_data_libraries_id'), table_name='tb_data_libraries')
    op.drop_table('tb_data_libraries')
    op.drop_index(op.f('ix_tb_data_borrow_records_id'), table_name='tb_data_borrow_records')
    op.drop_table('tb_data_borrow_records')
    op.drop_index(op.f('ix_tb_data_users_openid'), table_name='tb_data_users')
    op.drop_index(op.f('ix_tb_data_users_id'), table_name='tb_data_users')
    op.drop_table('tb_data_users')
    # ### end Alembic commands ###
