"""Add user profile fields

Revision ID: b6211c2af19d
Revises: 05cf4dc4d9ed
Create Date: 2025-02-09 21:28:57.430343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b6211c2af19d'
down_revision: Union[str, None] = '05cf4dc4d9ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_data_users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('tb_data_users', sa.Column('phone', sa.String(length=11), nullable=True))
    op.add_column('tb_data_users', sa.Column('bio', sa.String(length=500), nullable=True))
    op.alter_column('tb_data_users', 'nickname',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.create_index(op.f('ix_tb_data_users_email'), 'tb_data_users', ['email'], unique=True)
    op.create_index(op.f('ix_tb_data_users_phone'), 'tb_data_users', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_data_users_phone'), table_name='tb_data_users')
    op.drop_index(op.f('ix_tb_data_users_email'), table_name='tb_data_users')
    op.alter_column('tb_data_users', 'nickname',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               existing_nullable=True)
    op.drop_column('tb_data_users', 'bio')
    op.drop_column('tb_data_users', 'phone')
    op.drop_column('tb_data_users', 'email')
    # ### end Alembic commands ###
